name: ci-pipeline
on: 
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'checkout'
      uses: actions/checkout@v3
    - name: 'setup'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        scope: '@rprakashg'
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
    - run: npm install -g gatsby-cli
    - run: yarn install
    
    - name: 'publish'
      run: yarn run deploy
